[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# EVM version
evm_version = "paris"

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@chainlink/=lib/chainlink/",
    "forge-std/=lib/forge-std/src/"
]

# Test configuration
[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15

# Gas reporting
gas_reports = ["*"]

# Coverage
[profile.default.coverage]
via_ir = false

# RPC endpoints
[rpc_endpoints]
base = "${BASE_RPC_URL}"
mainnet = "${ETHEREUM_RPC_URL}"

# Etherscan verification
[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Formatter
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
